" Generated by vim-plug
" 四  2/25 17:19:48 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['coc.nvim'].commit = 'b38eb41a9fab3663dac915be38ffe7d8c841621f'
silent! let g:plugs['fzf'].commit = '298342677107f19f2ef7035afcf5302fdf26aa51'
silent! let g:plugs['fzf.vim'].commit = 'cc13a4b728c7b76c63e6dc42f320cec955d74227'
silent! let g:plugs['markdown-preview.nvim'].commit = 'c6bf4412b247ef09fab2adf3bc6f1056d0c57a4f'
silent! let g:plugs['nerdcommenter'].commit = '253eafd3a71ce2a48306fe4a7bdfc4208d0c2eb5'
silent! let g:plugs['quick-scope'].commit = '64a5e6f9791e75f4d87b176d5c11f31041aa4169'
silent! let g:plugs['rainbow'].commit = '4d15633cdaf61602e1d9fd216a77fc02e0881b2d'
silent! let g:plugs['tagbar'].commit = 'ed1bbe554d7ce4d9b6286ee3514ed4d3021408ee'
silent! let g:plugs['tagbar-javascript.vim'].commit = 'c388b4eb98cf1d732a1345df4b872a65f0609caa'
silent! let g:plugs['vim-airline'].commit = '06117a61e1218b2a866451d2ac4d8ddcd82c8543'
silent! let g:plugs['vim-airline-themes'].commit = '5cf03c355b64836ebcb681136539f48ada34f363'
silent! let g:plugs['vim-auto-save'].commit = '8c1d5dc919030aa712ad7201074ffb60961e9dda'
silent! let g:plugs['vim-bookmarks'].commit = '3adeae10639edcba29ea80dafa1c58cf545cb80e'
silent! let g:plugs['vim-delve'].commit = '554b7997caba5d2b38bc4a092e3a468e4abb7f18'
silent! let g:plugs['vim-devicons'].commit = '383159d338024f09e4d56585a9301958b6fefad6'
silent! let g:plugs['vim-floaterm'].commit = '74cf66dcb0f6b4e70a8b3c94870e1d1e1ca9e1f0'
silent! let g:plugs['vim-fugitive'].commit = '7bcfe539beee5fe8c542092732b6fd3786c6080e'
silent! let g:plugs['vim-go'].commit = '069113c1c03ec9330fbcccb36f79b268f8b88c1d'
silent! let g:plugs['vim-helm'].commit = '2c2e2e936607ed93f8f75de2066d04feff0e8e81'
silent! let g:plugs['vim-log-highlighting'].commit = '1037e26f3120e6a6a2c0c33b14a84336dee2a78f'
silent! let g:plugs['vim-markdown'].commit = '276524ed9c8aec415d3c6dbeec7c05fbd31c95ce'
silent! let g:plugs['vim-misc'].commit = '3e6b8fb6f03f13434543ce1f5d24f6a5d3f34f0b'
silent! let g:plugs['vim-notes'].commit = 'e465a0a987dbacdf7291688215b8545f8584d409'
silent! let g:plugs['vim-one'].commit = 'f8bcef1968f01842d92abbcb098ec28ad3931ea5'
silent! let g:plugs['vim-projectroot'].commit = '68787126ebbbe50e120e497ff63696b22f636840'
silent! let g:plugs['vim-rhubarb'].commit = 'd865e427d067af57d85cf2b7d2bc1912eb84d0bf'
silent! let g:plugs['vim-table-mode'].commit = '659ba4f39caa38e6913f88c9f4369c00e852160f'

PlugUpdate!

