k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    fullScreenLogs: false
    textWrap: true
    showTime: false
  currentContext: kind-vela-cluster
  currentCluster: kind-vela-cluster
  clusters:
    kind-vela-cluster:
      namespace:
        active: ""
        favorites:
        - vela-system
        - all
        - default
      view:
        active: traitdefinition
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    minikube:
      namespace:
        active: ""
        favorites:
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
